### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Blackspirits** [ghrlt/netflix-watchtime#2]
hi, 

i would like to know when you will add new features.

And I'd like it to be possible to add new languages. I am available to translate into Portuguese.

And please don't let the extension die, keep up the excellent work.

**Comment by ghrlt** [comment]
Hello @Blackspirits,

Thanks for your message! I think you will be happy to know that 773ef87 implements translations!
As of now, the extension is available in english (en) and french (fr). You, or anyone, may now add a traduction by following the little steps described in the [README](https://github.com/ghrlt/netflix-watchtime)

Have a great day
